services:
  frontend:
    image: frontend
    build:
      context: client
      dockerfile: ./Dockerfile
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
    environment:
      NODE_ENV: DEV
    ports:
      - 8080:8080